import { Post, Story, CharchaDebate, UserProfile, NotificationItem } from './types';

export const DEFAULT_GUEST_USER: UserProfile = {
  id: 'usr_guest',
  user_handle: 'citizen_bharat',
  full_name: 'Citizen of Bharat',
  avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
  bio: 'Exploring sovereign digital public infrastructure & Bharat research 🇮🇳',
  preferred_language: 'en',
  priority_matrix: {
    startups: 80,
    tech: 85,
    finance: 70,
    geopolitics: 75,
    culture: 60,
    mobility: 65,
  },
  is_professional: false,
  is_private: false,
  is_incognito: false,
  followers_count: 0,
  following_count: 0,
  verified: false,
};

export const INITIAL_CURRENT_USER: UserProfile = DEFAULT_GUEST_USER;

export const SEED_STORIES: Story[] = [
  {
    id: 'story_1',
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    user_handle: 'isro_community',
    user_name: 'ISRO Updates',
    avatar_url: 'https://images.unsplash.com/photo-1517976487507-5b3a4a8397a7?w=150&auto=format&fit=crop&q=80',
    media_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    video_url: 'https://assets.mixkit.co/videos/preview/mixkit-satellite-orbiting-the-earth-in-space-41908-large.mp4',
    text_content: '🚀 Chandrayaan science telemetry data now open to student researchers across Indian universities!',
    bg_color: '#081D34',
    is_watched: false,
  },
  {
    id: 'story_2',
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    user_handle: 'peak_bengaluru',
    user_name: 'Peak Bengaluru',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    media_url: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80',
    text_content: '⚡ Bangalore Namma Metro expands open ticketing via ONDC protocols. True sovereign tech interoperability!',
    bg_color: '#102A45',
    is_watched: false,
  },
  {
    id: 'story_3',
    created_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    user_handle: 'bharat_heritage',
    user_name: 'Sanskriti Bharat',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    media_url: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&auto=format&fit=crop&q=80',
    text_content: '🪔 Gujarat ancient stepwells restored with sustainable solar microgrids. Timeless architecture meets green energy.',
    bg_color: '#E85D04',
    is_watched: true,
  },
  {
    id: 'story_4',
    created_at: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    user_handle: 'ev_bharat',
    user_name: 'Clean Mobility India',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    video_url: 'https://assets.mixkit.co/videos/preview/mixkit-aerial-view-of-a-solar-panel-field-42903-large.mp4',
    text_content: '🇮🇳 India records highest monthly EV registrations: 120,000+ commercial and personal two-wheelers on roads.',
    bg_color: '#10B981',
    is_watched: true,
  },
];

export const SEED_POSTS: Post[] = [
  {
    id: 'post_1',
    created_at: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    user_handle: 'ananya_tech',
    user_name: 'Ananya Deshmukh',
    user_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    content_type: 'image',
    caption: 'India needs sovereign AI infrastructure, not just API wrappers on foreign foundational models. If our national datasets and vernacular wisdom train models hosted abroad, we surrender algorithmic sovereignty. We should establish a National Compute Grid funded like our telecom towers in the 2000s.',
    media_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1000&auto=format&fit=crop&q=80',
    video_url: 'https://assets.mixkit.co/videos/preview/mixkit-futuristic-city-with-traffic-at-night-42866-large.mp4',
    is_incognito: false,
    likes_count: 342,
    is_liked: false,
    tags: ['#tech', '#startups', '#geopolitics'],
    debates_count: 24,
    verified: true,
  },
  {
    id: 'post_2',
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    user_handle: 'fintech_bharat',
    user_name: 'Bharat Fintech Observer',
    user_avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    content_type: 'community',
    caption: 'UPI processed over 15 Billion transactions last month. With banks bearing infrastructure and fraud-prevention costs, how should the ecosystem sustain long-term infrastructure investment without burdening small merchants?',
    is_incognito: false,
    likes_count: 512,
    is_liked: true,
    tags: ['#finance', '#tech', '#startups'],
    debates_count: 48,
    verified: true,
    poll_data: {
      question: 'How should India finance long-term UPI infrastructure costs?',
      total_votes: 1840,
      user_voted_option_id: 'opt_1',
      options: [
        { id: 'opt_1', text: 'Keep 0% MDR, fund via Government Sovereign Digital Grant', votes: 1120 },
        { id: 'opt_2', text: 'Tiered micro-fee only on transactions > ₹2,000', votes: 540 },
        { id: 'opt_3', text: 'Optional value-add services & credit lines for merchants', votes: 180 },
      ],
    },
  },
  {
    id: 'post_3',
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    user_handle: 'startup_pulse',
    user_name: 'Indie Bharat Capital',
    user_avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    content_type: 'oneshot',
    caption: '15s Flash Analysis: Why Tier-2 Indian hubs (Indore, Coimbatore, Surat, Jaipur) are outpacing metros in hardware startup capital efficiency.',
    is_incognito: false,
    likes_count: 289,
    is_liked: false,
    tags: ['#startups', '#geopolitics', '#mobility'],
    debates_count: 15,
    verified: true,
    oneshot_data: {
      title: 'Tier-2 Bharat: The Hardware & Manufacturing Frontier',
      category: 'Startups & Economy',
      summary: 'Lower operational overhead, direct proximity to industrial clusters, and sticky local talent pools give Tier-2 founders a 40% burn advantage.',
      duration_seconds: 15,
      video_url: 'https://assets.mixkit.co/videos/preview/mixkit-engineers-working-on-a-solar-project-42905-large.mp4',
      slides: [
        {
          id: 'slide_1',
          title: '1. 40% Lower Burn Multiple',
          content: 'Co-working and industrial lease rates in Coimbatore and Indore run at ~1/3 of Bengaluru or Gurugram, extending runway by 8-12 months.',
          highlight: 'Cost Advantage',
          bg_gradient: 'from-amber-600 to-orange-700',
          media_url: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&auto=format&fit=crop&q=80',
        },
        {
          id: 'slide_2',
          title: '2. Proximity to Supply Chains',
          content: 'Precision machining in Rajkot, textile automation in Surat, and electronics assembly in Noida allow rapid physical prototyping in 48 hours.',
          highlight: 'Speed to Market',
          bg_gradient: 'from-blue-700 to-indigo-900',
          video_url: 'https://assets.mixkit.co/videos/preview/mixkit-circuit-board-working-components-41843-large.mp4',
        },
        {
          id: 'slide_3',
          title: '3. Sticky Vernacular Talent',
          content: 'Founders report 70% lower annual attrition in Tier-2 engineering hubs compared to metro hyper-poaching cycles.',
          highlight: 'Team Longevity',
          bg_gradient: 'from-emerald-700 to-teal-900',
        },
      ],
    },
  },
  {
    id: 'post_4',
    created_at: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    user_handle: 'incognito_thinker',
    user_name: 'Citizen 7842',
    user_avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    content_type: 'text',
    caption: 'Posting as an Incognito Citizen: There is an underreported issue in tech hiring where Indian vernacular talent is filtered out solely due to English accent nuances, despite superior algorithmic problem-solving skills. Social platforms need to champion vernacular-first code explanations.',
    is_incognito: true,
    likes_count: 678,
    is_liked: false,
    tags: ['#tech', '#culture'],
    debates_count: 53,
    verified: false,
  },
  {
    id: 'post_5',
    created_at: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
    user_handle: 'sanskritik_bharat',
    user_name: 'Sanskriti & Architecture',
    user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    content_type: 'image',
    caption: 'Modern Indian architecture must rediscover indigenous climate-responsive designs. Jharokhas, stepwells, and central courtyards provided natural cooling for centuries without energy-intensive HVAC loads.',
    media_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1000&auto=format&fit=crop&q=80',
    is_incognito: false,
    likes_count: 421,
    is_liked: true,
    tags: ['#culture', '#geopolitics'],
    debates_count: 18,
    verified: true,
  },
];

export const SEED_DEBATES: Record<string, CharchaDebate[]> = {
  post_1: [
    {
      id: 'deb_1_1',
      created_at: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
      post_id: 'post_1',
      user_handle: 'vikram_semicon',
      user_name: 'Vikramaditya Rao',
      user_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      argument: 'Completely agree. Look at what happened with GPS vs NavIC. When international tensions rise, foreign cloud providers can cut off GPU clusters overnight. Sovereign compute is as crucial as food security or national defense.',
      vote_agree: true,
      is_incognito: false,
      citations: ['https://pib.gov.in/PressReleasePage.aspx?PRID=1987654'],
      upvotes_count: 142,
      is_upvoted: true,
    },
    {
      id: 'deb_1_2',
      created_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
      post_id: 'post_1',
      user_handle: 'prashant_vc',
      user_name: 'Prashant Iyer',
      user_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      argument: 'Respectfully disagree on the state-owned compute model. Government hardware procurement cycles take 18-24 months, while AI chip generations change every 12 months. It is far more efficient to provide compute vouchers to founders for private cloud clusters.',
      vote_agree: false,
      is_incognito: false,
      citations: ['https://niti.gov.in/reports/ai-mission-compute'],
      upvotes_count: 98,
      is_upvoted: false,
    },
    {
      id: 'deb_1_3',
      created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
      post_id: 'post_1',
      user_handle: 'citizen_8891',
      user_name: 'Citizen 8891',
      argument: 'We should adopt a hybrid Public-Private Partnership (PPP) model, similar to C-DAC and private hyperscalers. That ensures both sovereign data custody and rapid hardware refresh cycles.',
      vote_agree: true,
      is_incognito: true,
      citations: [],
      upvotes_count: 67,
      is_upvoted: false,
    },
  ],
  post_2: [
    {
      id: 'deb_2_1',
      created_at: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
      post_id: 'post_2',
      user_handle: 'kirana_voice',
      user_name: 'Small Retailers Alliance',
      user_avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
      argument: 'Zero MDR was the single catalyst that made 50 million street vendors accept digital payments. The moment a 0.5% fee is introduced, cash will return overnight in vegetable markets and small tea stalls.',
      vote_agree: true,
      is_incognito: false,
      citations: ['https://rbi.org.in/Scripts/PublicationReportDetails.aspx?UrlPage=&ID=1214'],
      upvotes_count: 231,
      is_upvoted: true,
    },
    {
      id: 'deb_2_2',
      created_at: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
      post_id: 'post_2',
      user_handle: 'banking_analyst',
      user_name: 'Banking Insights India',
      user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      argument: 'Banks spend upwards of ₹5,000 Crores annually on UPI server switches, cybersecurity, and disputed refunds. A micro-fee on transactions above ₹5,000 only for large corporate merchants is reasonable and will protect retail consumers.',
      vote_agree: false,
      is_incognito: false,
      citations: ['https://npci.org.in/statistics'],
      upvotes_count: 115,
      is_upvoted: false,
    },
  ],
  post_4: [
    {
      id: 'deb_4_1',
      created_at: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
      post_id: 'post_4',
      user_handle: 'indic_coder',
      user_name: 'Indic AI Community',
      user_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      argument: '100% true. Some of the most prolific systems engineers and competitive programmers communicate comfortably in Hindi, Telugu, or Tamil. Translating technical documentation and normalizing vernacular tech demos is critical for Bharat 2047.',
      vote_agree: true,
      is_incognito: false,
      citations: [],
      upvotes_count: 189,
      is_upvoted: true,
    },
  ],
};

export const SEED_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    type: 'consensus',
    user_handle: 'charcha_system',
    text: 'Bharat Voice Consensus reached 78% agreement on the Sovereign Compute debate!',
    post_id: 'post_1',
    is_read: false,
  },
  {
    id: 'notif_2',
    created_at: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    type: 'debate',
    user_handle: 'vikram_semicon',
    user_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    text: 'submitted a counter-argument to a post you follow: "Sovereign compute is as crucial as food security..."',
    post_id: 'post_1',
    is_read: false,
  },
  {
    id: 'notif_3',
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    type: 'like',
    user_handle: 'ananya_tech',
    user_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    text: 'liked your Priority Matrix configuration on #tech and #startups.',
    is_read: true,
  },
  {
    id: 'notif_4',
    created_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    type: 'follow',
    user_handle: 'sanskritik_bharat',
    user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    text: 'started following your sovereign tech research stream.',
    is_read: true,
  },
];
